routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Route::resource('admin','Admin\AdminController', ['middleware' => ['auth', 'admin'],'except' => ['show']]);

Route::group(['prefix' => 'admin','middleware' => ['auth', 'admin']], function () {


	Route::resource('empresas','Admin\EmpresasAdminController', ['except' => ['show']]);

    Route::resource('manage_entrenamientos','Admin\EntrenamientosController', ['except' => ['show','create']]);
    
	Route::resource('planes','Admin\PlanesAdminController', ['except' => ['show']]);
	 Route::get('{id}/destroy', 
    [ 'uses' => 'Admin\PlanesAdminController@destroy',
    'as' => 'admin.planes.destroy']);

	 Route::get('uploadedFile/{filename}',['uses' => 'Admin\EmpresasAdminController@getFile',
    'as' => 'viewfiles']);

	 Route::resource('facturas','Admin\FacturasAdminController', ['except' => ['show']]);


	 
    Route::resource('ordenes','Admin\OrdenesController', ['except' => ['show']]);

    Route::get('ordenes/{id}',array('as'=>'ordenes.show','uses'=>'Admin\OrdenesController@show'));




});



Route::resource('gymadmin','Gymadmin\GymAdminController', ['middleware' => ['auth', 'gymadmin'],'except' => ['show']]);

Route::group(['prefix' => 'gymadmin','middleware' => ['auth', 'gymadmin']], function () {

	Route::get('perfil',['uses' => 'Gymadmin\ProfileController@index',
    'as' => 'gymadmin.profile.index']);

	Route::get('myuser',['uses' => 'Gymadmin\UsersController@edit',
    'as' => 'gymadmin.myuser.edit']);
    Route::put('myuser/update',['uses' => 'Gymadmin\UsersController@update',
    'as' => 'gymadmin.myuser.update']);
    Route::put('empresas/update',['uses' => 'Gymadmin\ProfileController@updateempresas',
    'as' => 'gymadmin.empresas.update']);

    Route::resource('entrenamientos','Gymadmin\EntrenamientosController', ['except' => ['show']]);


    Route::put('entrenamientos/{id}/update',['uses' => 'Gymadmin\EntrenamientosController@update',
    'as' => 'gymadmin.entrenamientos.update']);
    Route::get('entrenamientos/{id}/destroy', 
    [ 'uses' => 'Gymadmin\EntrenamientosController@destroy',
    'as' => 'gymadmin.entrenamientos.destroy']);

   
    Route::resource('servicios','Gymadmin\ServiciosController', ['except' => ['show']]);
    Route::get('servicios/{id}/destroy', 
    [ 'uses' => 'Gymadmin\ServiciosController@destroy',
    'as' => 'gymadmin.servicios.destroy']);

    Route::put('servicios/{id}/update',['uses' => 'Gymadmin\ServiciosController@update',
    'as' => 'gymadmin.servicios.update']);

    Route::resource('ingresos','Gymadmin\IngresosController', ['except' => ['show']]);
    Route::get('ingresos/{id}/destroy', 
    [ 'uses' => 'Gymadmin\IngresosController@destroy',
    'as' => 'gymadmin.ingresos.destroy']);

    Route::put('ingresos/{id}/update',['uses' => 'Gymadmin\IngresosController@update',
    'as' => 'gymadmin.ingresos.update']);

    Route::resource('egresos','Gymadmin\EgresosController', ['except' => ['show']]);
    Route::get('egresos/{id}/destroy', 
    [ 'uses' => 'Gymadmin\EgresosController@destroy',
    'as' => 'gymadmin.egresos.destroy']);

    Route::put('egresos/{id}/update',['uses' => 'Gymadmin\EgresosController@update',
    'as' => 'gymadmin.egresos.update']);

    Route::resource('resoluciones','Gymadmin\ResolucionesController', ['except' => ['show']]);
    Route::get('resoluciones/{id}/destroy', 
    [ 'uses' => 'Gymadmin\ResolucionesController@destroy',
    'as' => 'gymadmin.resoluciones.destroy']);

    Route::put('resoluciones/{id}/update',['uses' => 'Gymadmin\ResolucionesController@update',
    'as' => 'gymadmin.resoluciones.update']);

    Route::get('configuracion',['uses' => 'Gymadmin\ConfigController@index',
    'as' => 'gymadmin.config.index']);

    Route::group(['prefix' => 'gymadmin','middleware' => ['auth', 'gymadmin']], function () {

        Route::get('configuracion_general',['uses' => 'Gymadmin\ConfigController@configgeneral',
    'as' => 'gymadmin.config.general']);

        Route::get('mi_negocio',['uses' => 'Gymadmin\ConfigController@minegocio',
    'as' => 'gymadmin.config.general.minegocio']);

        Route::put('mi_negocio/update',['uses' => 'Gymadmin\ConfigController@minegocioup',
    'as' => 'gymadmin.config.general.minegocio.update']);

    });

    // Route::resource('facturas','Gymadmin\FacturasGymadminController', ['except' => ['show']]);
   

});


Route::get('/logout',
 'Auth\LoginController@logout');

Auth::routes();


Route::get('/home', 'HomeController@index')->name('home');

app/servicios.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class servicios extends Model
{
    protected $table="servicios";	
   	protected $fillable= ['id','nombre','dias','hora_desde','hora_hasta','fecha_inic','fecha_final','identificacion'];

   	
   	public function empresas()
   {

  return $this->belongsToMany('App\empresas','identificacion');

   }
}

app/Http/Controllers/Gymadmin/ConfigController.php
<?php

namespace App\Http\Controllers\Gymadmin;
use App\empresas;
use Auth;
use Illuminate\Support\Facades\DB;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;

class ConfigController extends Controller
{
   
   public function index(Request $request)
    {
    	return view('gymadmin.configuracion.index');
	}

	public function configgeneral(Request $request)
    {
    	return view('gymadmin.configuracion.configgeneral.index');
	}

	public function minegocio(Request $request)
    {
    	$user= Auth::user()->identificacion;
    	$empresas= empresas::find($user);
    	return view('gymadmin.configuracion.configgeneral.minegocio.index')->with('empresas', $empresas);
	}
		                                     
	} 

app/Http/Controllers/Gymadmin/EgresosController.php
<?php

namespace App\Http\Controllers\Gymadmin;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use App\egresos;
use App\User;
use App\empresas;
use Auth;
use Laracasts\Flash\Flash;
use Illuminate\Support\Facades\DB;

class EgresosController extends Controller
{
   public function index(Request $request)
    {
    	$identificacion = Auth::user()->identificacion;
		
		$egresos= DB::table('egresos')
                
                ->join('empresas', 'egresos.identificacion', '=', 'empresas.identificacion')
                
                ->select('egresos.*','empresas.razon_social')->where('egresos.identificacion','=', $identificacion)
                ->orderBy('id','ASC')->get();
		 return view('gymadmin.egresos.index')
		 ->with('egresos', $egresos);
		                                     
	}

    public function create(Request $request)
    {
			
	 return view('gymadmin.egresos.create');
		                                     

	}

	public function store(Request $request){
			
	 $egresos= new egresos($request->all());
	 $egresos->identificacion = Auth::user()->identificacion;
     $egresos->save();

     Flash::success("Se ha registrado el Egreso ". $egresos->nombre. " de forma existosa");

     return back();
		                                     

	}

	public function edit(Request $request, $id){
		$identificacion = Auth::user()->identificacion;
		$egresos = egresos::find($id);



		if ($egresos->identificacion == $identificacion ) {

			return view('gymadmin.egresos.edit')
			->with('id', $id)
			->with('egresos', $egresos);
		}

		else{
	 
			abort(404);                                
	}
		}


		public function update(Request $request, $id){


		$identificacion = Auth::user()->identificacion;
		$egresos = egresos::find($id);




		if ($egresos->identificacion == $identificacion ) {

			$egresos->nombre = $request->nombre;
			$egresos->save();

			 Flash::success("Se ha actualizado el Egreso ". $egresos->id. " de forma existosa"); 

              return back();      
		}

		else{
	 
			abort(404);                                
	}
		}


		public function destroy($id){

				$identificacion = Auth::user()->identificacion;
				$egresos= egresos::find($id);
    				
		  	  if ($egresos->identificacion == $identificacion ) {
				$egresos= egresos::find($id);
			  		$egresos->delete();
			  		Flash::warning('El Egreso '.$egresos->id.' ha sido borrado');
			  		return back();    
				}

			else{
		 
				abort(404);                                
				}	 
    	}
}

app/Http/Controllers/Gymadmin/EntrenamientosController.php
<?php

namespace App\Http\Controllers\Gymadmin;

use App\Http\Controllers\Controller;
use App\entrenamientos;
use App\User;
use App\empresas;
use Auth;
use Laracasts\Flash\Flash;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\DB;

class EntrenamientosController extends Controller
{
	
	public function index(Request $request)
    {
    	$identificacion = Auth::user()->identificacion;
		
		$entrenamientos= DB::table('entrenamientos')
                
                ->join('empresas', 'entrenamientos.identificacion', '=', 'empresas.identificacion')
                
                ->select('entrenamientos.*','empresas.razon_social')->where('entrenamientos.identificacion','=', $identificacion)
                ->orderBy('id','ASC')->get();
		 return view('gymadmin.entrenamientos.index')
		 ->with('entrenamientos', $entrenamientos);
		                                     
	}

    public function create(Request $request)
    {
			
	 return view('gymadmin.entrenamientos.create');
		                                     

	}

	public function store(Request $request){
			
	 $entrenamientos= new entrenamientos($request->all());
	 $entrenamientos->identificacion = Auth::user()->identificacion;
     $entrenamientos->save();

     Flash::success("Se ha registrado el entrenamiento ". $entrenamientos->nombre. " de forma existosa");

     return back();
		                                     

	}

	public function edit(Request $request, $id){
		$identificacion = Auth::user()->identificacion;
		$entrenamientos = entrenamientos::find($id);



		if ($entrenamientos->identificacion == $identificacion ) {

			return view('gymadmin.entrenamientos.edit')
			->with('id', $id)
			->with('entrenamientos', $entrenamientos);
		}

		else{
	 
			abort(404);                                
	}
		}


		public function update(Request $request, $id){


		$identificacion = Auth::user()->identificacion;
		$entrenamientos = entrenamientos::find($id);




		if ($entrenamientos->identificacion == $identificacion ) {

			$entrenamientos->nombre = $request->nombre;
			$entrenamientos->save();

			 Flash::success("Se ha actualizado el entrenamiento ". $entrenamientos->id. " de forma existosa"); 

              return back();      
		}

		else{
	 
			abort(404);                                
	}
		}


		public function destroy($id){

				$identificacion = Auth::user()->identificacion;
				$entrenamientos= entrenamientos::find($id);
    				
		  		

			  if ($entrenamientos->identificacion == $identificacion ) {
				$entrenamientos= entrenamientos::find($id);
			  		$entrenamientos->delete();
			  		Flash::warning('El entrenamiento '.$entrenamientos->id.' ha sido borrado');
			  		return back();    
				}

			else{
		 
				abort(404);                                
				}	 
    	}





		  
}

app/Http/Controllers/Gymadmin/GymAdminController.php
<?php

namespace App\Http\Controllers\Gymadmin;
use App\Http\Controllers\Controller;

use Illuminate\Http\Request;

class GymAdminController extends Controller
{
    public function index (Request $request){

		return view ('gymadmin.dashboard');
		 
		  }
}

app/Http/Controllers/Gymadmin/IngresosController.php
<?php

namespace App\Http\Controllers\Gymadmin;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use App\ingresos;
use App\User;
use App\empresas;
use Auth;
use Laracasts\Flash\Flash;
use Illuminate\Support\Facades\DB;

class IngresosController extends Controller
{
   public function index(Request $request)
    {
    	$identificacion = Auth::user()->identificacion;

		$ingresos= DB::table('ingresos')
                ->join('empresas', 'ingresos.identificacion', '=', 'empresas.identificacion')
                ->select('ingresos.*','empresas.razon_social')->where('ingresos.identificacion','=', $identificacion)
                ->orderBy('id','ASC')->get();
		 return view('gymadmin.ingresos.index')
		 ->with('ingresos', $ingresos);
		                                     
	}
	public function create(Request $request)
    {
			
	 return view('gymadmin.ingresos.create');
		                                     

	}
	public function store(Request $request){
			
	 $ingresos= new ingresos($request->all());
	 $ingresos->identificacion = Auth::user()->identificacion;
     $ingresos->save();

     Flash::success("Se ha registrado el Ingreso ". $ingresos->nombre. " de forma existosa");

     return back();
		                                     

	}

	public function edit(Request $request, $id){
		$identificacion = Auth::user()->identificacion;
		$ingresos = ingresos::find($id);


		if ($ingresos->identificacion == $identificacion ) {

			return view('gymadmin.ingresos.edit')
			->with('id', $id)
			->with('ingresos', $ingresos);
		}

		else{
	 
			abort(404);                                
	}
		}


		public function update(Request $request, $id){


		$identificacion = Auth::user()->identificacion;
		$ingresos = ingresos::find($id);




		if ($ingresos->identificacion == $identificacion ) {

			$ingresos->nombre = $request->nombre;
			$ingresos->save();

			 Flash::success("Se ha actualizado el Ingreso ". $ingresos->id. " de forma existosa"); 

              return back();      
		}

		else{
	 
			abort(404);                                
	}
		}


		public function destroy($id){

				$identificacion = Auth::user()->identificacion;
				$ingresos= ingresos::find($id);
    				
		  		

			  if ($ingresos->identificacion == $identificacion ) {
				$ingresos= ingresos::find($id);
			  		$ingresos->delete();
			  		Flash::warning('El Ingreso '.$ingresos->id.' ha sido borrado');
			  		return back();    
				}

			else{
		 
				abort(404);                                
				}	 
    	}
}

app/Http/Controllers/Gymadmin/ProfileController.php
<?php

namespace App\Http\Controllers\Gymadmin;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use App\User;
use App\empresas;
use Auth;
use Laracasts\Flash\Flash;
use Illuminate\Support\Facades\Hash;
use Illuminate\Support\Facades\DB;
use App\Http\Requests\Gymadmin\MyuserRequest;

class ProfileController extends Controller
{
    public function index (Request $request){

        $identificacion= Auth::user()->identificacion;

        $ordenes= DB::table('ordenes')
                
                ->join('empresas', 'ordenes.identificacion', '=', 'empresas.identificacion')
                ->join('planes', 'ordenes.id_plan', '=', 'planes.id')
               
                ->select('ordenes.*','empresas.razon_social', 'planes.nombre', 'planes.detalles', 'empresas.identificacion')->where('ordenes.identificacion', '=',$identificacion)
                ->orderBy('id','ASC')->first();
               
    	$empresa = DB::table('users')
                
                ->join('empresas', 'users.identificacion', '=', 'empresas.identificacion')
               
                ->select('empresas.*','razon_social')
                ->orderBy('id','ASC')->first();

        $empresas = empresas::find($identificacion);

    	 $user= Auth::user()->id;
    	 $users = User::find($user);


    	 
		return view ('gymadmin.perfil.index')
		->with('users', $users)
		->with('empresa', $empresa)
        ->with('ordenes', $ordenes)
        ->with('empresas', $empresas);
		 
	}

    public function updateempresas (Request $request){

        $identificacion= Auth::user()->identificacion;

        $empresas= empresas::find($identificacion);
                $empresas->tipo_de_identificacion = $request->tipo_de_identificacion;
                $empresas->identificacion = $request->identificacion;
                $empresas->dv = $request->dv;
                $empresas->razon_social = $request->razon_social;
                $empresas->departamento = $request->departamento;
                $empresas->ciudad = $request->ciudad;
                $empresas->departamento = $request->departamento;
                $empresas->direccion = $request->direccion;
                $empresas->telefono = $request->telefono;
                $empresas->emailfac = $request->emailfac;
                $empresas->save();


         
            Flash::success('La empresa '.$empresas->razon_social. ' ha sido actualizada con exito');
                return back();
    }
}

app/Http/Controllers/Gymadmin/UsersController.php
<?php

namespace App\Http\Controllers\Gymadmin;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use App\User;
use Auth;
use Laracasts\Flash\Flash;
use Illuminate\Support\Facades\Hash;
use Illuminate\Support\Facades\DB;
use App\Http\Requests\Gymadmin\userrequest;

class UsersController extends Controller
{
    public function edit (Request $request){

    	 $user= Auth::user()->id;
    	 $users = User::find($user);
    	 
		return view ('gymadmin.myuser.edit')
		->with('users', $users);
		 
	}
	public function update (userrequest $request){

		$users= User::find(Auth::user()->id);
		
		  	$users->name = $request->name;
		  	$users->email = $request->email;

		  	if ($request->password == '') {
		  		$users->save();
		  	}

		  	else{
		  		$users->password = Hash::make($request->password);
		  		$users->save();
		  	}
		Flash::success('Tu usuario '.$users->name. ' ha sido actualizada con exito');
		  		return back();
		 	
	}



}

resources/views/gymadmin/servicios/create.blade.php
@extends('template.gymadmin.main')
@section('titulo', 'Añadir servicios')


@section('content')


<div class="container-fluid">
                <!-- Start Page Content -->
                <div class="row">
                    <div class="col-12">
                        <div class="card">
                            <div class="card-body">
                            {!! Form::open(['route' => 'servicios.store', 'method' => 'POST']) !!} 
                                <h4 class="card-title">Información Básica</h4>
                                <p class="text-muted m-b-15 f-s-12">Información Entrenamientos</p>
                                <div class="row p-t-20">
                                    <div class="col-sm-4">
                                        <div class="form-group">                              
                                        {!! Form::label('nombre','NOMBRE')!!}
                                            {!!Form::text('nombre',null, ['class' => 'form-control input-rounded', 'placeholder' => 'Nombre' , 'required']) !!}
                                         </div>
                                    </div>

                                    <div class="col-sm-3">
                                        <div class= "form-group">                              
                                        {!! Form::label('Personal','Personal')!!}
                                            {!!Form::select('tipo_de_identificacion', ['Seleccione','Pepito Perez' => 'Pepito Perez'],null,['class' => 'form-control input-rounded', 'id'=>'personal','required'])!!}
                                         </div>
                                    </div> 
                                    <div class="col-sm-3">
                                        <div class= "form-group">                              
                                        {!! Form::label('tasadepago','Tasa de pago')!!}
                                            {!!Form::select('tasadepago', ['Seleccione'],null,['class' => 'form-control input-rounded', 'id'=>'tasadepago','required'])!!}
                                         </div>
                                    </div> 

                                </div>

                                <hr>

                                <h4 class="card-title">Horarios</h4><br>

                                <div class="col-sm-5 " align="center">
                                        <div class= "form-group">                              
                                        <div class="btn-group" data-toggle="buttons">
            
                                            <label class="btn btn-success active">
                                                L
                                                <input name='dias[]' type="checkbox" autocomplete="off" checked value="L">
                                                <span class="glyphicon glyphicon-ok"></span>
                                            </label>

                                            <label class="btn btn-primary">
                                                M
                                                <input type="checkbox" name="dias[]"autocomplete="off" value="M">
                                                <span class="glyphicon glyphicon-ok"></span>
                                            </label>            
                                        
                                            <label class="btn btn-info">
                                                M
                                                <input type="checkbox" name="dias[]" autocomplete="off" value="X">
                                                <span class="glyphicon glyphicon-ok"></span>
                                            </label>            
                                        
                                            <label class="btn btn-primary">
                                                J
                                                <input type="checkbox" name="dias[]" autocomplete="off" value="J">
                                                <span class="glyphicon glyphicon-ok"></span>
                                            </label>            

                                            <label class="btn btn-warning">
                                                V
                                                <input type="checkbox"  name="dias[]"autocomplete="off" value="V">
                                                <span class="glyphicon glyphicon-ok"></span>
                                            </label>            
                                        
                                            <label class="btn btn-success">
                                                S
                                                <input type="checkbox" name="dias[]" autocomplete="off" value="S">
                                                <span class="glyphicon glyphicon-ok"></span>
                                            </label> 
                                            <label class="btn btn-danger">
                                                D
                                                <input type="checkbox" name="dias[]" autocomplete="off" value="D">
                                                <span class="glyphicon glyphicon-ok"></span>
                                            </label>            
                                        
                                        </div>
                                         </div>
                                         <div class="row p-t-20">

                                         <div class="col-sm-5">
                                            <div class= "form-group">                              
                                        {!! Form::label('hora_desde','Hora desde')!!}
                                            {!!Form::time('hora_desde',null,['class' => 'form-control input-rounded', 'id'=>'horadesde','required'])!!}
                                         </div> 
                                          </div>
                                          <div class="col-sm-5">
                                            <div class= "form-group">                              
                                        {!! Form::label('hora_hasta','Hora Hasta')!!}
                                            {!!Form::time('hora_hasta',null,['class' => 'form-control input-rounded', 'id'=>'tasadepago','required'])!!}
                                         </div>
                                          </div>
                                        </div>
                                        <div class="row p-t-20">

                                         <div class="col-sm-5">
                                            <div class= "form-group">                              
                                        {!! Form::label('fecha_inic','Fecha Inicial')!!}
                                            {!!Form::date('fecha_inic',null,['class' => 'form-control input-rounded', 'id'=>'fecha_inic','required', 'step'=>'0.01'])!!}
                                         </div> 
                                          </div>
                                          <div class="col-sm-5">
                                            <div class= "form-group">                              
                                        {!! Form::label('fecha_final','Fecha Final')!!}
                                            {!!Form::date('fecha_final',null,['class' => 'form-control input-rounded', 'id'=>'fecha_final','required'])!!}
                                         </div>
                                          </div>

                                          
                                        </div>
                                    </div> 
                                <button type="submit" class="btn btn-success"> <i class="fa fa-check"></i> Guardar</button>


                            </div>
                        </div>
                    </div>
                </div>
                <!-- End PAge Content -->
            </div>

@endsection            

resources/views/gymadmin/servicios/index.blade.php
@extends('template.gymadmin.main')

@section('titulo', 'Servicios')
@section('content')

<div class="container-fluid">
                <!-- Start Page Content -->
                <div class="row">
                    <div class="col-12">
						<div class="card">
                            <div class="card-body">
                                <h4 class="card-title">Servicios</h4>
                                <h6 class="card-subtitle">Todos los servicios</h6>
                                <div class="table-responsive m-t-40">
                                    <table id="myTable" class="table table-bordered table-striped">
                                        <thead>
                                            <tr>
                                                <th>ID</th>
                                                <th>NOMBRE</th>
                                                <th>DIAS ASIGNADOS</th>
                                                <th>FECHA CREACIÓN</th>
                                                <th>ULTIMA ACTUALIZACIÓN</th>
                                                <th>ACCIÓN</th>
                                            </tr>
                                        </thead>
                                        <tbody>
                                            @foreach($servicios as $servicio)
                                            <tr>
                                                <td>{{$servicio->id}}</td>
                                              <td>{{$servicio->nombre}}</td>
                                              <td>{{$servicio->dias}}</td>
                                              <td>{{$servicio->created_at}}</td>
                                              <td>{{$servicio->updated_at}}</td>
                                              <td><a href="{{ route('servicios.edit', $servicio->id) }}" class="btn btn-warning btn-xs" ><span class="fa fa-pencil"> </a><a href="{{route('gymadmin.servicios.destroy' , $servicio->id )}}" target="" class="btn btn-danger btn-xs" ><span class="fa fa-trash"> </a> </td>
                                        </tbody>
                                        @endforeach
                                    </table>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>            
@endsection