routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Route::resource('admin','Admin\AdminController', ['middleware' => ['auth', 'admin'],'except' => ['show']]);

Route::group(['prefix' => 'admin','middleware' => ['auth', 'admin']], function () {


	Route::resource('empresas','Admin\EmpresasAdminController', ['except' => ['show']]);

    Route::resource('manage_entrenamientos','Admin\EntrenamientosController', ['except' => ['show','create']]);
    
	Route::resource('planes','Admin\PlanesAdminController', ['except' => ['show']]);
	 Route::get('{id}/destroy', 
    [ 'uses' => 'Admin\PlanesAdminController@destroy',
    'as' => 'admin.planes.destroy']);

	 Route::get('uploadedFile/{filename}',['uses' => 'Admin\EmpresasAdminController@getFile',
    'as' => 'viewfiles']);

	 Route::resource('facturas','Admin\FacturasAdminController', ['except' => ['show']]);


	 
    Route::resource('ordenes','Admin\OrdenesController', ['except' => ['show']]);

    Route::get('ordenes/{id}',array('as'=>'ordenes.show','uses'=>'Admin\OrdenesController@show'));




});



Route::resource('gymadmin','Gymadmin\GymAdminController', ['middleware' => ['auth', 'gymadmin'],'except' => ['show']]);

Route::group(['prefix' => 'gymadmin','middleware' => ['auth', 'gymadmin']], function () {

	Route::get('perfil',['uses' => 'Gymadmin\ProfileController@index',
    'as' => 'gymadmin.profile.index']);

	Route::get('myuser',['uses' => 'Gymadmin\UsersController@edit',
    'as' => 'gymadmin.myuser.edit']);
    Route::put('myuser/update',['uses' => 'Gymadmin\UsersController@update',
    'as' => 'gymadmin.myuser.update']);
    Route::put('empresas/update',['uses' => 'Gymadmin\ProfileController@updateempresas',
    'as' => 'gymadmin.empresas.update']);

    Route::resource('entrenamientos','Gymadmin\EntrenamientosController', ['except' => ['show']]);


    Route::put('entrenamientos/{id}/update',['uses' => 'Gymadmin\EntrenamientosController@update',
    'as' => 'gymadmin.entrenamientos.update']);
    Route::get('entrenamientos/{id}/destroy', 
    [ 'uses' => 'Gymadmin\EntrenamientosController@destroy',
    'as' => 'gymadmin.entrenamientos.destroy']);

   
    Route::resource('servicios','Gymadmin\ServiciosController', ['except' => ['show']]);
    Route::get('servicios/{id}/destroy', 
    [ 'uses' => 'Gymadmin\ServiciosController@destroy',
    'as' => 'gymadmin.servicios.destroy']);

    Route::put('servicios/{id}/update',['uses' => 'Gymadmin\ServiciosController@update',
    'as' => 'gymadmin.servicios.update']);

    Route::resource('ingresos','Gymadmin\IngresosController', ['except' => ['show']]);
    Route::get('ingresos/{id}/destroy', 
    [ 'uses' => 'Gymadmin\IngresosController@destroy',
    'as' => 'gymadmin.ingresos.destroy']);

    Route::put('ingresos/{id}/update',['uses' => 'Gymadmin\IngresosController@update',
    'as' => 'gymadmin.ingresos.update']);

    Route::resource('egresos','Gymadmin\EgresosController', ['except' => ['show']]);
    Route::get('egresos/{id}/destroy', 
    [ 'uses' => 'Gymadmin\EgresosController@destroy',
    'as' => 'gymadmin.egresos.destroy']);

    Route::put('egresos/{id}/update',['uses' => 'Gymadmin\EgresosController@update',
    'as' => 'gymadmin.egresos.update']);

    Route::resource('resoluciones','Gymadmin\ResolucionesController', ['except' => ['show']]);
    Route::get('resoluciones/{id}/destroy', 
    [ 'uses' => 'Gymadmin\ResolucionesController@destroy',
    'as' => 'gymadmin.resoluciones.destroy']);

    Route::put('resoluciones/{id}/update',['uses' => 'Gymadmin\ResolucionesController@update',
    'as' => 'gymadmin.resoluciones.update']);

    Route::get('configuracion',['uses' => 'Gymadmin\ConfigController@index',
    'as' => 'gymadmin.config.index']);

    Route::group(['prefix' => 'gymadmin','middleware' => ['auth', 'gymadmin']], function () {

        Route::get('configuracion_general',['uses' => 'Gymadmin\ConfigController@configgeneral',
    'as' => 'gymadmin.config.general']);

        Route::get('mi_negocio',['uses' => 'Gymadmin\ConfigController@minegocio',
    'as' => 'gymadmin.config.general.minegocio']);

        Route::put('mi_negocio/update',['uses' => 'Gymadmin\ConfigController@minegocioup',
    'as' => 'gymadmin.config.general.minegocio.update']);

    });

    // Route::resource('facturas','Gymadmin\FacturasGymadminController', ['except' => ['show']]);
   

});


Route::get('/logout',
 'Auth\LoginController@logout');

Auth::routes();


Route::get('/home', 'HomeController@index')->name('home');

app/entrenamientos.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class entrenamientos extends Model
{
    protected $table="entrenamientos";	
   	protected $fillable= ['id','nombre','identificacion'];

   	public function empresas()
   {

  return $this->belongsToMany('App\empresas','identificacion');

   }
}

app/Http/Controllers/Admin/EntrenamientosController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Controller;

use App\entrenamientos;
use App\User;
use App\empresas;
use Auth;
use Laracasts\Flash\Flash;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\DB;

class EntrenamientosController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        
        $entrenamientos= DB::table('entrenamientos')
                
                ->join('empresas', 'entrenamientos.identificacion', '=', 'empresas.identificacion')
                
                ->select('entrenamientos.*','empresas.razon_social')->where('entrenamientos.default','=', 1)
                ->orderBy('id','ASC')->get();
         return view('admin.entrenamientos.index')
         ->with('entrenamientos', $entrenamientos);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
      // $this->validate($request, [
      //       'nombre' => 'required'
      //   ]);
      //   entrenamientos::create($request->all());
      //   return;


        dd($request->all());
     
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }
}

app/Http/Controllers/Gymadmin/EntrenamientosController.php
<?php

namespace App\Http\Controllers\Gymadmin;

use App\Http\Controllers\Controller;
use App\entrenamientos;
use App\User;
use App\empresas;
use Auth;
use Laracasts\Flash\Flash;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\DB;

class EntrenamientosController extends Controller
{
	
	public function index(Request $request)
    {
    	$identificacion = Auth::user()->identificacion;
		
		$entrenamientos= DB::table('entrenamientos')
                
                ->join('empresas', 'entrenamientos.identificacion', '=', 'empresas.identificacion')
                
                ->select('entrenamientos.*','empresas.razon_social')->where('entrenamientos.identificacion','=', $identificacion)
                ->orderBy('id','ASC')->get();
		 return view('gymadmin.entrenamientos.index')
		 ->with('entrenamientos', $entrenamientos);
		                                     
	}

    public function create(Request $request)
    {
			
	 return view('gymadmin.entrenamientos.create');
		                                     

	}

	public function store(Request $request){
			
	 $entrenamientos= new entrenamientos($request->all());
	 $entrenamientos->identificacion = Auth::user()->identificacion;
     $entrenamientos->save();

     Flash::success("Se ha registrado el entrenamiento ". $entrenamientos->nombre. " de forma existosa");

     return back();
		                                     

	}

	public function edit(Request $request, $id){
		$identificacion = Auth::user()->identificacion;
		$entrenamientos = entrenamientos::find($id);



		if ($entrenamientos->identificacion == $identificacion ) {

			return view('gymadmin.entrenamientos.edit')
			->with('id', $id)
			->with('entrenamientos', $entrenamientos);
		}

		else{
	 
			abort(404);                                
	}
		}


		public function update(Request $request, $id){


		$identificacion = Auth::user()->identificacion;
		$entrenamientos = entrenamientos::find($id);




		if ($entrenamientos->identificacion == $identificacion ) {

			$entrenamientos->nombre = $request->nombre;
			$entrenamientos->save();

			 Flash::success("Se ha actualizado el entrenamiento ". $entrenamientos->id. " de forma existosa"); 

              return back();      
		}

		else{
	 
			abort(404);                                
	}
		}


		public function destroy($id){

				$identificacion = Auth::user()->identificacion;
				$entrenamientos= entrenamientos::find($id);
    				
		  		

			  if ($entrenamientos->identificacion == $identificacion ) {
				$entrenamientos= entrenamientos::find($id);
			  		$entrenamientos->delete();
			  		Flash::warning('El entrenamiento '.$entrenamientos->id.' ha sido borrado');
			  		return back();    
				}

			else{
		 
				abort(404);                                
				}	 
    	}





		  
}

resources/views/admin/entrenamientos/create.blade.php
<form method="POST" v-on:submit.prevent="createKeep">
<div class="modal fade" id="create">
	<div class="modal-dialog">
		<div class="modal-content">
			<div class="modal-header">
				<button type="button" class="close" data-dismiss="modal" aria-label="Close">
					<span>&times;</span>
				</button>
				<h4>Crear</h4>
			</div>
			<div class="modal-body">
				<label for="keep">Nueva Tarea</label>
				<input type="text" name="nombre" class="form-control" v-model="newManage_entrenamientos">
				<span v-for="error in errors" class="text-danger">@{{ error }}</span>
			</div>
			<div class="modal-footer">
				<input type="submit" class="btn btn-primary" value="Guardar">
			</div>
		</div>
	</div>
</div>
</form>

resources/views/admin/entrenamientos/index.blade.php
@extends('template.admin.main')

@section('titulo', 'Entrenamientos')
@section('content')



<div class="container-fluid" id="crud">
    



                <!-- Start Page Content -->
                <div class="row">
                    <div class="col-12">
						<div class="card">
                            <div class="card-body">
                                <h4 class="card-title">Entrenamientos</h4>

                                <h6 class="card-subtitle">Todos los entrenamientos</h6>
                                

                                <div class="box">
                                    <div>
                                        <p>
                                            <a href="#" class="btn btn-success btn pull-right" data-toggle="modal" data-target="#create">
                                                <span class="icon is-small">
                                                    <i class="fa fa-plus" style="color: white"></i>
                                                </span>
                                                <span style="color: white;">Añadir nuevo entrenamiento</span>
                                            </a>
                                        </p>
                                    </div><br>
                                
                                <div class="table-responsive m-t-40">
                                    
                                    <table id="myTable" class="table table-bordered table-striped">
                                        <thead>
                                            <tr>
                                                <th>ID</th>
                                                <th>NOMBRE</th>
                                                <th>FECHA CREACIÓN</th>
                                                <th>ULTIMA ACTUALIZACIÓN</th>
                                                <th>ACCIÓN</th>
                                            </tr>
                                        </thead>
                                        <tbody>
                                            @foreach($entrenamientos as $entrenamiento)
                                            <tr>
                                                <td>{{$entrenamiento->id}}</td>
                                              <td>{{$entrenamiento->nombre}}</td>
                                              <td>{{$entrenamiento->created_at}}</td>
                                              <td>{{$entrenamiento->updated_at}}</td>
                                              <td><a href="{{ route('manage_entrenamientos.edit', $entrenamiento->id) }}" class="btn btn-warning btn-xs" ><span class="fa fa-pencil"> </a><a href="{{route('manage_entrenamientos.destroy' , $entrenamiento->id )}}" target="" class="btn btn-danger btn-xs" ><span class="fa fa-trash"> </a> </td>
                                        </tbody>
                                        @endforeach
                                    </table>


                                </div>
                            </div>
                                @include('admin.entrenamientos.create')
                        </div>
                        
                    </div>
                </div>

            </div> 


          
@endsection

@section('js')

<script>

new Vue({
    el: '#crud',
    created: function() {
        this.getKeeps();
    },
    data: {
        keeps: [],
        pagination: {
            'total': 0,
            'current_page': 0,
            'per_page': 0,
            'last_page': 0,
            'from': 0,
            'to': 0
        },
        newManage_entrenamientos: '',
        fillKeep: {'id': '', 'nombre': '', 'identificacion': '','default': '1' },
        errors: '',
        offset: 3,
    },
    computed: {
        isActived: function() {
            return this.pagination.current_page;
        },
        pagesNumber: function() {
            if(!this.pagination.to){
                return [];
            }

            var from = this.pagination.current_page - this.offset; 
            if(from < 1){
                from = 1;
            }

            var to = from + (this.offset * 2); 
            if(to >= this.pagination.last_page){
                to = this.pagination.last_page;
            }

            var pagesArray = [];
            while(from <= to){
                pagesArray.push(from);
                from++;
            }
            return pagesArray;
        }
    },
    methods: {
        getKeeps: function(page) {
            var urlKeeps = 'tasks?page='+page;
            axios.get(urlKeeps).then(response => {
                this.keeps = response.data.tasks.data,
                this.pagination = response.data.pagination
            });
        },
        editKeep: function(keep) {
            this.fillKeep.id   = keep.id;
            this.fillKeep.keep = keep.keep;
            $('#edit').modal('show');
        },
        updateKeep: function(id) {
            var url = 'tasks/' + id;
            axios.put(url, this.fillKeep).then(response => {
                this.getKeeps();
                this.fillKeep = {'id': '', 'keep': ''};
                this.errors   = [];
                $('#edit').modal('hide');
                toastr.success('Tarea actualizada con éxito');
            }).catch(error => {
                this.errors = 'Corrija para poder editar con éxito'
            });
        },
        deleteKeep: function(keep) {
            var url = 'tasks/' + keep.id;
            axios.delete(url).then(response => { //eliminamos
                this.getKeeps(); //listamos
                toastr.success('Eliminado correctamente'); //mensaje
            });
        },
        createKeep: function() {
            var url = 'manage_entrenamientos';
            axios.post(url, {
                nombre: this.newManage_entrenamientos
            }).then(response => {
                this.getKeeps();
                this.newManage_entrenamientos = '';
                this.errors = [];
                $('#create').modal('hide');
                toastr.success('Nueva tarea creada con éxito');
            }).catch(error => {
                this.errors = 'Corrija para poder crear con éxito'
            });
        },
        changePage: function(page) {
            this.pagination.current_page = page;
            this.getKeeps(page);
        }
    }
});
















</script>
@endsection